apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gitops-example
  name: gitops-example
  namespace: simple-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gitops-example
  strategy: {}
  template:
    metadata:
      labels:
        run: gitops-example
    spec:
      containers:
      - image: nginx
        name: gitops-example
        resources: {}
status: {}
